services:
  scrappystats:
    build:
      context: ./current
      dockerfile: Dockerfile
    container_name: scrappystats
    env_file: 
      - .env
    volumes:
      - ./config:/config
    restart: unless-stopped
